chore:third test husky&lint-staged

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,4 +1,14 @@
-#!/bin/sh
-. "$(dirname "$0")/_/husky.sh"
-echo "Hello from pre-commit" >> .husky/pre-commit
-pnpm lint-staged
+pnpm lint-staged || {
+    echo "❌❌ Lint-staged Check Failed' ❌❌ ";
+        false;
+}
+
+pnpm build || (
+    echo '❌👷🔨❌ Better call Uncle Bob... Because your build failed ❌👷🔨❌
+          Next build failed: View the errors above to see why.
+    '
+    false;
+)
+
+# If everything passes... Now we can commit
+echo '✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅'
